FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./packages/backend/package*.json ./packages/backend/
COPY ./packages/shared/package*.json ./packages/shared/

RUN npm ci backend

COPY ./packages/backend ./packages/backend
COPY ./packages/shared ./packages/shared
RUN npm run build -w backend

EXPOSE 4000

CMD [ "node", "packages/backend/dist/app.js" ]