FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./packages/frontend/package*.json ./packages/frontend/
COPY ./packages/shared/package*.json ./packages/shared/

RUN npm ci frontend

COPY ./packages/frontend ./packages/frontend
COPY ./packages/shared ./packages/shared

ARG APP_TODO_API
ENV REACT_APP_TODO_API=${APP_TODO_API}
RUN npm run build -w frontend

EXPOSE 3000

CMD [ "npx", "serve", "packages/frontend/build" ]